config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'user#index'
##Product
  get 'products/index', to: 'products#index', as: 'admindashboard'
  get 'products/new', to: 'products#new', as: 'new_product'
  post 'products', to: 'products#create'
  get 'products/:id',to: 'products#show', as: 'product' 
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  put '/products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'

  ###product_category
  get 'products/:id/product_categories/new', to: 'product_categories#new', as: 'new_category'
  post'products/:id/product_categories', to: 'product_categories#create', as: 'categories'
  get 'products/:id/product_categories/index', to: 'product_categories#index', as: 'list_categories'
  delete '/product_category/:id', to: 'product_categories#destroy', as: 'delete_product_category'
  get 'product_category/:id/edit', to: 'product_categories#edit', as: 'edit_product_category'
  put 'product_category/:id', to: 'product_categories#update',as: 'product_category'
   get 'product_category/buy_item/:id',to: 'product_categories#buy_item', as: 'buy_item'
   post 'product_category/confirm/:id', to: 'product_categories#buy_confirmation', as: 'buy_confirm'
   get 'product_category/:id',to: 'product_categories#show', as: 'ProductCategory'


  ####User View
  get 'user/index', to: 'user#index', as: 'homepage'
  get 'user/buyCategoryList/:id', to: 'user#buyCategoryList', as: 'buyCategoryList'
  get 'user/show_cart', to: 'user#show_cart', as: 'show_cart'
 get 'user/pdf_generator/:id',to: 'user#pdf_generator', as: 'pdf_generator'
 get 'user/payment_suceess', to: "user#payment_success", as: "payment_success"
  #get  'user/search', as: 'search_page'
 
  post 'user/search_result',to: 'user#search_result', as: 'search_result'
   #get 'user/show_category_list/:id', to: 'user#show_category_list', as: 'showCategoryList'
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	 mount_uploaders :images, ImageUploader
    belongs_to :product
    has_many :carts, dependent: :destroy
    has_and_belongs_to_many :orders
    validates :name, presence: true, uniqueness: { case_sensitive: false } 
    validates :price, presence: true, numericality: {message: "allowed only numbers" }
    validates :quantity, presence: true, numericality: { message: "allowed only integer numbers", only_integer: true }
    validates :description, presence: true
    scope :find_category_by_product,-> (product_id) { where("product_id = ? ",product_id)}
    scope :find_category,-> (search_data) { where("lower(name) LIKE ?","%#{search_data}%") }

end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
        skip_before_filter :verify_authenticity_token   
         layout 'admin/adminDashboard',only: [:index]
        DELIVERY_CHARGES = 100
    def new
        render layout: "admin/adminDashboard"
        @ProductCategory=ProductCategory.new
      end

      def create
        @product=Product.find(params[:id])
        @ProductCategory=@product.product_categories.new(category_params)
        if @ProductCategory.save
            redirect_to list_categories_path(@product)
        else
            render :new
        end
      end

      def index
          @product=Product.find(params[:id])
      end

      def edit
       
          @ProductCategory=ProductCategory.find(params[:id])
             render layout: "admin/adminDashboard"
              @ProductCategory
      end
    
      def update
        @ProductCategory=ProductCategory.find(params[:id])
        if(@ProductCategory.update(category_params))
          flash[:notice] = "record updated!!!!"
          redirect_to list_categories_path(@ProductCategory.product_id)
        else
          render :edit
        end 
      end  

      def destroy
        @product_category=ProductCategory.find(params[:id])
        product_id= @product_category.product_id
        @product_category.destroy
        redirect_to list_categories_path(product_id)
      end

      def buy_item
         @product_category=ProductCategory.find(params[:id])
         unless user_signed_in?
             redirect_to new_user_session_path
         end
        if user_signed_in?
            redirect_to ProductCategory_path(@product_category)
        end
      end

      def show
        @product_category=ProductCategory.find(params[:id])
       render layout: "home_layout"
       @product_category
      end

      def buy_confirmation
        @product_category=ProductCategory.find(params[:id])
        @quantity=params[:confirm][:quantity].to_i
        if @quantity == 0
          flash[:notice]="select quantity"
          redirect_to :back
        else
            if @quantity > @product_category.quantity
              flash[:notice]="to many orders.."
              redirect_to :back
            else
                @product_category.quantity = (@product_category.quantity.to_i) - @quantity
                @product_category.save!
                @Net_price = calculate_total_bill(@product_category,@quantity)
                Cart.create(buy_date: Date.today, product_category_id:@product_category.id, quantity: @quantity,net_price: @Net_price)
                flash[:notice] = "product added into card.."
                redirect_to homepage_path
        end
      end
   end

   

   def calculate_total_bill(product_category,quantity)
      total_amount=product_category.price * quantity
      gst = product_category.GST.to_i
      gst_amount= ( total_amount * gst ) / 100
      @Net_price = total_amount + gst_amount
   end
  
      private
      def category_params
        params.require(:ProductCategory).permit(:name,:price,:quantity,:description,{images: []})
      end

end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/views/product_categories/partials/_category_form.html.erb
             <div class="input-group">
                 <%= f.label :'Category Name'%><br>
                 <%= f.text_field :name %>
            </div>

            <div class="input-group">
                <%= f.label :'Price'%><br>
                <%= f.text_field :price %>
            </div>

            <div class="input-group">    
                <%= f.label :'Quantity'%><br>
                <%= f.text_field :quantity %>
            </div>
            <div class="input-group">
            <%= f.label :'Description'%><br>
            <%= f.text_area :description %>
            </div>

            <div class="input-group">
            <%= f.label :'Upload image'%><br>
            <%= f.file_field :images , multiple: true%>
            </div>

             <div class="input-group">
                <%= f.submit(:save, {class: 'btn btn-success'})%>
                <%=link_to 'cancel', admindashboard_path %>
            </div>

app/views/product_categories/partials/_search_result.html.erb
<% categories.each do |categoryObj|%>
	<% if categoryObj.quantity && categoryObj.quantity.to_i > 0 %>
	             	 <div class="col-sm-3 col-md-4 col-lg-4">
	             		<div class="well">
	                                <h3><%= categoryObj.name %></h3>
	                                <% categoryObj.images.each do |c|%>
                                	<%= image_tag(c.thumb.url) %>
                                	<% end %>
	                                <p>Price <%= categoryObj.price %></p>
	                                <p>Description <%= categoryObj.description %></p>
	                                <p><%= link_to 'Buy',buy_item_path(categoryObj) %></p>            
	            	     </div>
	       			</div>	

	    <% end %>
	   
<% end %>


		

app/views/product_categories/partials/_slidebar.html.erb
<% @categories = ProductCategory.all.paginate(:page => params[:search], :per_page => 3)%>
<div class="pagination">
		<%= will_paginate @categories, param_name: "search" %>
	</div>
	<br>
<% @categories.each do |categoryObj|%>
	<% if categoryObj.quantity && categoryObj.quantity.to_i > 0 %>
	             	 <div class="col-sm-12 col-md-3 col-lg-4">
	             		<div class="well">
	             			
	                                <h3><%= categoryObj.name %></h3>
	                                <% categoryObj.images.each do |c|%>
                                	<%= image_tag(c.thumb.url) %>
                                	<% end %>
	                                <b>Price</b> <%= categoryObj.price %>
	                               <!--  <p>Description <%= categoryObj.description %></p> -->
	                                <%= link_to 'Add to Cart',buy_item_path(categoryObj)%>
	            	    		 
	       					</div>	
						</div>	
	    	<% end %>
	   
	<% end %>
	