config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'user#index'
##Product
  get 'products/index', to: 'products#index', as: 'admindashboard'
  get 'products/new', to: 'products#new', as: 'new_product'
  post 'products', to: 'products#create'
  get 'products/:id',to: 'products#show', as: 'product' 
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  put '/products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'

  ###product_category
  get 'products/:id/product_categories/new', to: 'product_categories#new', as: 'new_category'
  post'products/:id/product_categories', to: 'product_categories#create', as: 'categories'
  get 'products/:id/product_categories/index', to: 'product_categories#index', as: 'list_categories'
  delete '/product_category/:id', to: 'product_categories#destroy', as: 'delete_product_category'
  get 'product_category/:id/edit', to: 'product_categories#edit', as: 'edit_product_category'
  put 'product_category/:id', to: 'product_categories#update',as: 'product_category'
   get 'product_category/buy_item/:id',to: 'product_categories#buy_item', as: 'buy_item'
   post 'product_category/confirm/:id', to: 'product_categories#buy_confirmation', as: 'buy_confirm'
   get 'product_category/:id',to: 'product_categories#show', as: 'ProductCategory'


  ####User View
  get 'user/index', to: 'user#index', as: 'homepage'
  get 'user/buyCategoryList/:id', to: 'user#buyCategoryList', as: 'buyCategoryList'
  get 'user/show_cart', to: 'user#show_cart', as: 'show_cart'
 get 'user/pdf_generator/:id',to: 'user#pdf_generator', as: 'pdf_generator'
 get 'user/payment_suceess', to: "user#payment_success", as: "payment_success"
  #get  'user/search', as: 'search_page'
 
  post 'user/search_result',to: 'user#search_result', as: 'search_result'
   #get 'user/show_category_list/:id', to: 'user#show_category_list', as: 'showCategoryList'
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	 mount_uploaders :images, ImageUploader
    belongs_to :product
    has_many :carts, dependent: :destroy
    has_and_belongs_to_many :orders
    validates :name, presence: true, uniqueness: { case_sensitive: false } 
    validates :price, presence: true, numericality: {message: "allowed only numbers" }
    validates :quantity, presence: true, numericality: { message: "allowed only integer numbers", only_integer: true }
    validates :description, presence: true
    scope :find_category_by_product,-> (product_id) { where("product_id = ? ",product_id)}
    scope :find_category,-> (search_data) { where("lower(name) LIKE ?","%#{search_data}%") }

end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
        skip_before_filter :verify_authenticity_token   
         layout 'admin/adminDashboard',only: [:index]
        DELIVERY_CHARGES = 100
    def new
        render layout: "admin/adminDashboard"
        @ProductCategory=ProductCategory.new
      end

      def create
        @product=Product.find(params[:id])
        @ProductCategory=@product.product_categories.new(category_params)
        if @ProductCategory.save
            redirect_to list_categories_path(@product)
        else
            render :new
        end
      end

      def index
          @product=Product.find(params[:id])
      end

      def edit
       
          @ProductCategory=ProductCategory.find(params[:id])
             render layout: "admin/adminDashboard"
              @ProductCategory
      end
    
      def update
        @ProductCategory=ProductCategory.find(params[:id])
        if(@ProductCategory.update(category_params))
          flash[:notice] = "record updated!!!!"
          redirect_to list_categories_path(@ProductCategory.product_id)
        else
          render :edit
        end 
      end  

      def destroy
        @product_category=ProductCategory.find(params[:id])
        product_id= @product_category.product_id
        @product_category.destroy
        redirect_to list_categories_path(product_id)
      end

      def buy_item
         @product_category=ProductCategory.find(params[:id])
         unless user_signed_in?
             redirect_to new_user_session_path
         end
        if user_signed_in?
            redirect_to ProductCategory_path(@product_category)
        end
      end

      def show
        @product_category=ProductCategory.find(params[:id])
       render layout: "home_layout"
       @product_category
      end

      def buy_confirmation
        @product_category=ProductCategory.find(params[:id])
        @quantity=params[:confirm][:quantity].to_i
        if @quantity == 0
          flash[:notice]="select quantity"
          redirect_to :back
        else
            if @quantity > @product_category.quantity
              flash[:notice]="to many orders.."
              redirect_to :back
            else
                @product_category.quantity = (@product_category.quantity.to_i) - @quantity
                @product_category.save!
                @Net_price = calculate_total_bill(@product_category,@quantity)
                Cart.create(buy_date: Date.today, product_category_id:@product_category.id, quantity: @quantity,net_price: @Net_price)
                flash[:notice] = "product added into card.."
                redirect_to homepage_path
        end
      end
   end

   

   def calculate_total_bill(product_category,quantity)
      total_amount=product_category.price * quantity
      gst = product_category.GST.to_i
      gst_amount= ( total_amount * gst ) / 100
      @Net_price = total_amount + gst_amount
   end
  
      private
      def category_params
        params.require(:ProductCategory).permit(:name,:price,:quantity,:description,{images: []})
      end

end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/views/product_categories/edit.html.erb
<div class="container">
      <div class="card">
      	<h2>Edit Catergory</h2>
        <%= form_for :ProductCategory, url: product_category_path, method: :put do |f| %>
           <%= render partial: 'product_categories/partials/category_form', locals: {f: f }%>
            </div>
        <% end %>
    </div>
</div>

app/views/product_categories/index.html.erb
<div class="container">
            <h2><%= @product.product_name %>
            <%= link_to 'New Category', new_category_path(@product),class: 'btn btn-success'%></h2>
             
            <%if @product.product_categories.empty?%>
                <p class="notice">List Not Found!</p>
            
            <% else %>
                    <% @product.product_categories.each do |category|%>
                            <div class="col-sm-12 col-md-3 col-lg-4">
                            <div class="well">
                                <h3><%= category.name %></h3>
                                
                                <% category.images.each do |c|%>
                                <%= image_tag(c.thumb.url) %>
                                <% end %><br>
                                <p><b>Price :- </b> <%= category.price %></p>
                                <p><b>Quantity :- </b><%= category.quantity %></p>
                               <!--  <p><b>Description :-</b><%= category.description %> -->
                                <p><%= link_to 'Edit', edit_product_category_path(category) %>
                                <%= link_to 'Delete', delete_product_category_path(category), method: :delete, data: {confirm: 'Are You Sure?'} %></p>
                            </div>
                            </div>
                    <% end %>
            <% end %>
</div>    

app/views/product_categories/new.html.erb
<div class="container">
    <div class="card">
            <h2>Add Catergory</h2>
            <%= form_for :ProductCategory, url: categories_path do |f| %>

            <%= render partial: 'product_categories/partials/category_form', locals: {f: f }%>           
        <% end %>
    </div>
</div>

app/views/product_categories/show.html.erb
<div class="container">
	<div class="card">
	<%= form_for :confirm , url: buy_confirm_path(@product_category) do |f| %>
    	 
    	  <div class= "flash-messages" >
           <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
  		</div>	<br>
  		<h3><%= @product_category.name %></h3>
    	 <p align="center"><% @product_category.images.each do |c|%>
	            <%= image_tag(c.thumb.url) %><br>
	     <% end %></p>
	     <b>Price</b> <%= @product_category.price %>
	     <p><b>Description</b> <%= @product_category.description %></p>
	     <b>Quantity:-</b> 	<%= f.text_field(:quantity)%><br><br>
	     <p align="left"><%= f.submit "confirm", class:"btn-success" %><br>
   <% end %>
    </div>
</div>