config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'user#index'
##Product
  get 'products/index', to: 'products#index', as: 'admindashboard'
  get 'products/new', to: 'products#new', as: 'new_product'
  post 'products', to: 'products#create'
  get 'products/:id',to: 'products#show', as: 'product' 
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  put '/products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'

  ###product_category
  get 'products/:id/product_categories/new', to: 'product_categories#new', as: 'new_category'
  post'products/:id/product_categories', to: 'product_categories#create', as: 'categories'
  get 'products/:id/product_categories/index', to: 'product_categories#index', as: 'list_categories'
  delete '/product_category/:id', to: 'product_categories#destroy', as: 'delete_product_category'
  get 'product_category/:id/edit', to: 'product_categories#edit', as: 'edit_product_category'
  put 'product_category/:id', to: 'product_categories#update',as: 'product_category'
   get 'product_category/buy_item/:id',to: 'product_categories#buy_item', as: 'buy_item'
   post 'product_category/confirm/:id', to: 'product_categories#buy_confirmation', as: 'buy_confirm'
   get 'product_category/:id',to: 'product_categories#show', as: 'ProductCategory'


  ####User View
  get 'user/index', to: 'user#index', as: 'homepage'
  get 'user/buyCategoryList/:id', to: 'user#buyCategoryList', as: 'buyCategoryList'
  get 'user/show_cart', to: 'user#show_cart', as: 'show_cart'
 get 'user/pdf_generator/:id',to: 'user#pdf_generator', as: 'pdf_generator'
 get 'user/payment_suceess', to: "user#payment_success", as: "payment_success"
  #get  'user/search', as: 'search_page'
 
  post 'user/search_result',to: 'user#search_result', as: 'search_result'
   #get 'user/show_category_list/:id', to: 'user#show_category_list', as: 'showCategoryList'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders,dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  before_save :set_default_role
  validates :firstname, :lastname,presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :mobile_number, presence: true, format: { with: /\A[0-9]{10}+\Z/, message: "only allows numbers " }
  
  protected
  def set_default_role
    if self.role.nil?
      self.role = "user"
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  protect_from_forgery with: :null_session
  layout 'home_layout'
  def index
    @products=SearchOperations.searchProduct
  end
  
  def buyCategoryList
     @product=Product.find(params[:id])
     # @product= Kaminari.paginate_array(@product).page(params[:page]).per(2)
  end

   def show_cart
   		@carts=Cart.all
    end

    def search_result
        if params[:search] == ""
          flash[:notice]="Search not found!!"
          redirect_to homepage_path
        else
           @categories=SearchOperations.searchCategories(params[:search].downcase)
           if @categories.present?
              @categories
               #= @categories.page(params[:page]).per(3)
           else
              flash[:notice]="Search not found!!"
              redirect_to homepage_path
           end
        end
    end

    def pdf_generator
      #render plain: params.inspect
       @cart=Cart.all
        respond_to do |format|
          format.html
          format.pdf do
            pdf = PdfGenerator.new(@cart)
            send_data pdf.render, filename: "#{@product_category}.pdf" , type: "application/pdf" ,
                            disposition: "inline"
           end
          @cart
        end
    end
end

app/helpers/user_helper.rb
module UserHelper
	def cart_count
		Cart.select(:id).all.count
	end
end

app/views/user/buyCategoryList.html.erb
<div class="container">
<% cnt= 0 %>
<%=link_to 'back', homepage_path %>
<br>
<% if @product.product_categories.present? %>
	<% @categories = @product.product_categories.paginate(:page => params[:search], :per_page => 3)%>
		<div class="pagination">
				<%= will_paginate @categories,param_name: "search" %>
		</div>
	<br>
	<h2><%= @product.product_name%></h2>
	<% @categories.each do |categoryObj|%>
	             	<% if categoryObj.quantity.to_i > 0 %>
	             	 <div class="col-sm-12 col-md-4 col-lg-4">
	             		<div class="well">
	                                <h3><%= categoryObj.name %></h3>
	                                <p><% categoryObj.images.each do |c|%>
	                                <%= image_tag(c.thumb.url) %>
	                                <% end %>
	                                <b>Price</b> <%= categoryObj.price %>
	                               <%= link_to 'Add to Cart',buy_item_path(categoryObj)%></p>            
	            	     </div>
	       			</div>
	                  <% else %>
	                     <% cnt = cnt + 1%>
	                <% end %>
	<% end %>
<% end %>
<% if cnt == @categories.length %>
	<div class="well">
     <p>No List Found...</p>
 </div>
<% end %>
</div>

app/views/user/buyList.html.erb
<% cnt= 0 %>
<% if @product.product_categories.present? %>
	<% @product.product_categories.each do |c|%>
	             	<% if c.quantity.to_i > 0 %>
	             	 <div class="col-sm-3 col-md-4 col-lg-4">
	             		<div class="well">
	                                <h3><%= c.name %></h3>
	                                <p>Price <%= c.price %></p>
	                                <p>Description <%= c.description %></p>
	                                <p><%= link_to 'Buy',buy_item_path(c) %></p>
	            	     </div>
	       			</div>
	                  <% else %>
	                     <% cnt = cnt + 1%>
	                <% end %>
	<% end %>
<% end %>
<% if cnt == @product.product_categories.length %>
	<div class="well">
     <p>No List Found...</p>
 </div>
<% end %>
	

app/views/user/index.html.erb
  <ul class="nav nav-tabs">
            <% @products.each do |p|%>
              <% if p.product_categories.present? %>
                
                  <% p.product_name[0] = p.product_name[0].capitalize %>
               <li><%= link_to "#{p.product_name}", buyCategoryList_path(p), id: 'list'%></li>
                
              <% end %>
            <% end %>
          </ul>

          <br><br><br><br><br>
  <div class= "flash-messages" >
           <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
  </div>   
        <div class="search-bar">
          <%= render "user/partials/search_form"%> 
        </div>

        <div class="container">
          <%= render "product_categories/partials/slidebar"%> 
        </div>
         

app/views/user/payment_success.html.erb
<div class="container">
	<div class="alert alert-success">
	  <strong>Payment has been done successfully !!</strong> <br/>
	</div>
	 <%= link_to 'OK' , homepage_path , class: "btn-lg btn-success"%>
	</div>

app/views/user/search_result.html.erb
<div class="container">
	
<% @categories.each do |categoryObj|%>
	<% if categoryObj.quantity && categoryObj.quantity.to_i > 0 %>
	  <div class="col-sm-12 col-md-3 col-lg-4">
	  	<div class="well">
	      <h3><%= categoryObj.name %></h3>
	      <% categoryObj.images.each do |c|%>
    	   	<%= image_tag(c.thumb.url) %>
				<% end %>
	      <p>Price <%= categoryObj.price %></p>
	      <p>Description <%= categoryObj.description %></p>
	      <p><%= link_to 'Add to Cart',buy_item_path(categoryObj)%></p>
	    </div>
	  </div>
	<% end %>
<% end %>
</div>

app/views/user/show_cart.html.erb
<div class="container">
      <div class="card">
       <h1>My Cart</h1>
       <% if @carts.present? %>
       <% total = 0%>
	       <% @carts.each do |cartObj|%>
	            <% @product_category=ProductCategory.find(cartObj.product_category_id)%>
	            <b><%=@product_category.name %></b><br/>
	            Original Price:- <%= @product_category.price%><br>
	            GST :- <%= @product_category.GST %><br>
	            Quantity :- <%= cartObj.quantity%><br/>
	            Net Price :- <%=cartObj.net_price %><br/>
	            Buy Date :- <%=cartObj.buy_date%><br/><hr>
	            <% total = total + cartObj.net_price%>
	        <% end %>
	        <p><b>Total :-</b> <%=total%></p>
	        <%= link_to "Pay Bill",payment_success_path, class: "btn-success"%>
	        <%= link_to "Cancel", homepage_path, class: "btn-success"%>
	        <%= link_to "Get Receipt (PDF)",  pdf_generator_path("bill_receipt", format: "pdf")%>
	    <% else %>
	    	<p>Your Cart is Empty!!!!</p>
	    <% end %>
 </div>

</div>