config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'user#index'
##Product
  get 'products/index', to: 'products#index', as: 'admindashboard'
  get 'products/new', to: 'products#new', as: 'new_product'
  post 'products', to: 'products#create'
  get 'products/:id',to: 'products#show', as: 'product' 
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  put '/products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'

  ###product_category
  get 'products/:id/product_categories/new', to: 'product_categories#new', as: 'new_category'
  post'products/:id/product_categories', to: 'product_categories#create', as: 'categories'
  get 'products/:id/product_categories/index', to: 'product_categories#index', as: 'list_categories'
  delete '/product_category/:id', to: 'product_categories#destroy', as: 'delete_product_category'
  get 'product_category/:id/edit', to: 'product_categories#edit', as: 'edit_product_category'
  put 'product_category/:id', to: 'product_categories#update',as: 'product_category'
   get 'product_category/buy_item/:id',to: 'product_categories#buy_item', as: 'buy_item'
   post 'product_category/confirm/:id', to: 'product_categories#buy_confirmation', as: 'buy_confirm'
   get 'product_category/:id',to: 'product_categories#show', as: 'ProductCategory'


  ####User View
  get 'user/index', to: 'user#index', as: 'homepage'
  get 'user/buyCategoryList/:id', to: 'user#buyCategoryList', as: 'buyCategoryList'
  get 'user/show_cart', to: 'user#show_cart', as: 'show_cart'
 get 'user/pdf_generator/:id',to: 'user#pdf_generator', as: 'pdf_generator'
 get 'user/payment_suceess', to: "user#payment_success", as: "payment_success"
  #get  'user/search', as: 'search_page'
 
  post 'user/search_result',to: 'user#search_result', as: 'search_result'
   #get 'user/show_category_list/:id', to: 'user#show_category_list', as: 'showCategoryList'
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :product_categories, dependent: :destroy
    validates :product_name, presence: true , uniqueness: { case_sensitive: false } 
    
    scope :find_product,-> (search_data){ where("lower(product_name) LIKE ?","%#{search_data}%").pluck(:id) }
    scope :product_search,-> { joins(:product_categories).where("quantity > ? ",0).uniq}
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :verify_authenticity_token  
  layout 'admin/adminDashboard'
  def index
    @products=Product.all
  end

  def new
    #render plain: params.inspect
    @product=Product.new
    respond_to do |format|
     format.html{render :partial => 'products/partials/new' ,locals: {product: @product} }
    end
  end

  def create
   # render plain: params.inspect
          @product=Product.new(product_params)
          if  @product.save
          redirect_to admindashboard_path
          else
            redirect_to :back
          end
    
  end

  def edit
    # render plain: params.inspect
    @product=Product.find(params[:pid].to_i)
     respond_to do |format|
     format.html{render :partial => 'products/partials/edit' ,locals: {product: @product} }
    end
  end

  def update
     #render plain: params.inspect
    @product=Product.find(params[:id])
    if(@product.update(product_params))
      redirect_to admindashboard_path
    else
      redirect_to :back
    end

  end


  def show
    @product=Product.find(params[:id])
  end

  def destroy
    @product=Product.find(params[:id])
    @product.destroy
    redirect_to admindashboard_path
  end
  private
  def product_params
      params.require(:product).permit(:product_name)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_edit.html.erb
    <%= form_for :product, url: product_path(@product), method: :put do |f| %>
            <%= render partial: "products/partials/form", locals: {f: f} %>
    <% end %>

app/views/products/_form.html.erb
		 <% if @product.errors.any?%>
            <% @product.errors.full_messages.each do |msg| %>
                <%= msg %>
                <% end %>
        <% end %>
        Product Name <%= f.text_field :product_name%>
        <%= f.submit(:save, {class: 'btn btn-success'}) %>
        <%=link_to 'cancel', admindashboard_path, class: 'btn btn-danger'%>



    

app/views/products/_new.html.erb
<%= form_for :product, url: products_path do |f| %>
             <%= render partial: "products/partials/form", locals: {f: f} %>
<% end %>

app/views/products/index.html.erb
<div class="container">
      <div class="card">
        <h3>Product Details</h3>
            <div class="product-btn">
    <%= link_to 'New Product', new_product_path,class: 'btn btn-success',id: 'new_product_id', remote: true %>
    </div>
    <div class="new-product-view">
            
    </div>
        <table class="table">
        <% @products.each do |p|%>
            <tr class="product-row">
                <td><%= p.product_name %></td>
                <td><%= link_to 'Edit',edit_product_path(p),class: 'edit-product', remote: true %></td>
                <td><%= link_to 'View',list_categories_path(p) %></td>
                <td><%= link_to 'Delete',delete_product_path(p),method: :delete, data: {confirm: 'Are You Sure?'}%></td>
           </tr>
        <% end %>
        </table>
 </div>
</div>